# Generated by Django 4.2 on 2024-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfil_correo_alter_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_usuario',
            name='tipo',
            field=models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
