# Generated by Django 4.2 on 2024-06-05 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipo_usuario_tipo_alter_comuna_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_banos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_hab',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
