# Generated by Django 4.2 on 2024-06-05 09:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_perfil_cuidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='m2_construido',
            field=models.FloatField(default=0, validators=[app.models.validate_min_value]),
        ),
    ]
