# Generated by Django 4.2 on 2024-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_inmueble_m2_construido'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
