# Generated by Django 4.2 on 2024-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nombre_inmueble',
            field=models.CharField(max_length=200),
        ),
    ]
