# Generated by Django 4.2 on 2024-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_inmueble_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
