# Generated by Django 4.2 on 2024-06-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_inmueble_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo_usuario',
        ),
    ]
